name: Install JS client

inputs:
  cache:
    description: Whether we should cache dependencies between workflow runs
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.cache == 'true'
      uses: actions/cache@v3
      with:
        path: ./clients/js/node_modules/
        key: ${{ runner.os }}-clients-js-${{ hashFiles('./clients/js/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-clients-js

    - name: Install dependencies
      working-directory: ./clients/js
      run: pnpm install --frozen-lockfile
      shell: bash
