import {
  base58PublicKey,
  createGenericFileFromBrowserFile,
  generateSigner,
  percentAmount,
  transactionBuilder,
} from "@lorisleiva/js";
import { createV1, mintV1, TokenStandard } from "@lorisleiva/mpl-digital-asset";
import { Inter } from "@next/font/google";
import { useWallet } from "@solana/wallet-adapter-react";
import dynamic from "next/dynamic";
import Head from "next/head";
import { FormEvent } from "react";
import { useMetaplex } from "./useMetaplex";

import styles from "@/styles/Home.module.css";
const inter = Inter({ subsets: ["latin"] });

const WalletMultiButtonDynamic = dynamic(
  async () =>
    (await import("@solana/wallet-adapter-react-ui")).WalletMultiButton,
  { ssr: false }
);

export default function Home() {
  const wallet = useWallet();
  const metaplex = useMetaplex();

  const onSubmit = async (event: FormEvent) => {
    event.preventDefault();
    const formData = new FormData(event.target as HTMLFormElement);
    const data = Object.fromEntries(formData) as { name: string; image: File };
    const imageFile = await createGenericFileFromBrowserFile(data.image);

    // Upload image and JSON data.
    const [imageUri] = await metaplex.uploader.upload([imageFile]);
    const uri = await metaplex.uploader.uploadJson({
      name: data.name,
      description: "A test NFT created using the Metaplex JS SDK.",
      image: imageUri,
    });

    // Create and mint NFT.
    const mint = generateSigner(metaplex);
    await transactionBuilder(metaplex)
      .add(
        createV1(metaplex, {
          mint,
          name: data.name,
          uri,
          sellerFeeBasisPoints: percentAmount(5.5, 2),
          tokenStandard: TokenStandard.NonFungible,
        })
      )
      .add(
        mintV1(metaplex, {
          mint: mint.publicKey,
          tokenStandard: TokenStandard.NonFungible,
          amount: 1,
        })
      )
      .sendAndConfirm();

    console.log({
      metaplex,
      uri,
      mint: base58PublicKey(mint.publicKey),
      ...data,
    });
  };

  return (
    <>
      <Head>
        <title>Create NFT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <WalletMultiButtonDynamic />
          </div>
        </div>

        <div className={styles.center}>
          {wallet.connected ? (
            <form method="post" onSubmit={onSubmit}>
              <label>
                Name: <input name="name" defaultValue="My NFT" />
              </label>
              <label>
                Image: <input name="image" type="file" />
              </label>
              <button type="submit">Submit form</button>
            </form>
          ) : (
            <p>Connect your wallet to create an NFT</p>
          )}
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
